lqvm: Fix validate_name pipe error handling
The grep in the pipe can error with a return code of 1 which just means
not found. Fix by testing $? = 1

Signed-off-by: Mark Grant <m.grant.prg@gmail.com>

diff --git a/src/prg/bash/lqvm/lqvm-snap.sh.in b/src/prg/bash/lqvm/lqvm-snap.sh.in
--- a/src/prg/bash/lqvm/lqvm-snap.sh.in
+++ b/src/prg/bash/lqvm/lqvm-snap.sh.in
@@ -73,6 +73,9 @@
 #				store format.				#
 # 28/11/2021	MG	1.0.4	Tighten SPDX tag.			#
 # 17/03/2022	MG	1.0.5	Add error checking to config file read.	#
+#				validate_name() should not error out of	#
+#				pipe if grep has exit code 1 which just	#
+#				means not found.			#
 #									#
 #########################################################################
 
@@ -386,11 +389,11 @@ validate_name()
 	local -i name_matches
 
 	name_matches=$(virsh -c $connect_uri list --all \
-		| grep "\<$name\>" | wc -l)
+		| { grep "\<$name\>" || test $?=1; } | wc -l)
 	std_cmd_err_handler $?
 	if (( !$name_matches )); then
 		output "No such VM $name" 1
-		script_exit 64
+		script_exit 77
 	fi
 }
 
