lqvm: Validate VM names before processing
Signed-off-by: Mark Grant <m.grant.prg@gmail.com>

diff --git a/src/prg/bash/lqvm/lqvms-backups.sh.in b/src/prg/bash/lqvm/lqvms-backups.sh.in
--- a/src/prg/bash/lqvm/lqvms-backups.sh.in
+++ b/src/prg/bash/lqvm/lqvms-backups.sh.in
@@ -67,6 +67,7 @@
 #				Refactor get username and password into	#
 #				function.				#
 #				Refactor perform backups.		#
+# 15/03/2022	MG	1.0.4	Validate VM names before processing.	#
 #									#
 #########################################################################
 
@@ -78,7 +79,7 @@ set -o pipefail
 ##################
 readonly outputprefix="$(basename $0):"
 
-readonly version=1.0.3				# Script version
+readonly version=1.0.4				# Script version
 readonly packageversion=@pkgversion@		# Package version
 
 readonly etclocation=@sysconfdir@		# Path to config directory
@@ -252,6 +253,42 @@ proc_CL()
 	vms="$@"
 }
 
+# Validate the VM name.
+# Parameters	1 - VM name
+# Return value - 0 on success, 77 on error.
+validate_vm_name()
+{
+	local -i name_matches
+
+	name_matches=$(virsh -c $connect_uri list --all \
+		| { grep "\<$1\>" || test $?=1; } | wc -l)
+	std_cmd_err_handler $?
+	if (( !$name_matches )); then
+		output "No such VM $1" 1
+		return 77
+	else
+		return 0
+	fi
+}
+
+# Validate VM names.
+# Parameters - None.
+# No return value.
+validate_vm_names()
+{
+	local ok=true
+
+	for vm in $vms; do
+		validate_vm_name $vm
+		if (( $? )); then
+			ok=false
+		fi
+	done
+	if ! $ok; then
+		script_exit 77
+	fi
+}
+
 # Determine if the VM is running.
 # Parameters	1 - VM.
 #		2 - Variable to receive the result.
@@ -395,6 +432,8 @@ perform_vms_backups()
 proc_config_file
 
 proc_CL "$@"
+
+validate_vm_names
 
 ensure_vms_not_running
 
