lxcu: Add Fedora support
Signed-off-by: Mark Grant <m.grant.prg@gmail.com>

diff --git a/src/prg/bash/lxcu/lxcu-create.sh.in b/src/prg/bash/lxcu/lxcu-create.sh.in
--- a/src/prg/bash/lxcu/lxcu-create.sh.in
+++ b/src/prg/bash/lxcu/lxcu-create.sh.in
@@ -88,6 +88,7 @@
 # 03/09/2021	MG	1.0.10	With lxc v4 lxc start and attach need	#
 #				slightly different privileges. The	#
 #				altered commands also work pre-v4.	#
+# 18/09/2021	MG	1.1.0	Add support for Fedora.			#
 #									#
 #########################################################################
 
@@ -100,7 +101,7 @@ set -o pipefail
 ##################
 readonly outputprefix="$(basename $0):"
 
-readonly version=1.0.10				# Script version
+readonly version=1.1.0				# Script version
 readonly packageversion=@pkgversion@		# Package version
 
 readonly hostetclocation=@sysconfdir@		# Path to config directory
@@ -341,7 +342,7 @@ network_config()
 	std_cmd_err_handler $?
 }
 
-# Create the specified type.
+# Create the specified type of APT container.
 # Parameters - $1 is the type to create.
 # No return value.
 create_deb_type()
@@ -362,7 +363,7 @@ create_deb_type()
 	fi
 }
 
-# Create an APT package distribution.
+# Create an APT container.
 # No parameters.
 # No return value.
 create_deb()
@@ -497,6 +498,106 @@ create_deb()
 	std_cmd_err_handler $?
 }
 
+# Create the specified type of Fedora container.
+# Parameters - $1 is the type to create.
+# No return value.
+create_fedora_type()
+{
+	# Install the development tools group.
+	if [[ $1 == "dev" ]]; then
+		systemd-run --quiet --user --scope -p "Delegate=yes" \
+			lxc-attach -n $name \
+			sudo dnf -- -y group install "Development Tools"
+		std_cmd_err_handler $?
+	fi
+
+	if [[ -e $etclocation/$dist/$rel/$1/install.list ]]; then
+		cat $etclocation/$dist/$rel/$1/install.list \
+			| xargs systemd-run --quiet --user --scope \
+			-p "Delegate=yes" lxc-attach -n $name \
+			sudo dnf -- -y install
+		std_cmd_err_handler $?
+	fi
+	if [[ -e $etclocation/$dist/$rel/$1/cache.list ]]; then
+		cat $etclocation/$dist/$rel/$1/cache.list \
+			| xargs systemd-run --quiet --user --scope \
+			-p "Delegate=yes" lxc-attach -n $name \
+			sudo dnf -- -y install --downloadonly
+		std_cmd_err_handler $?
+	fi
+}
+
+# Create a Fedora container.
+# No parameters.
+# No return value.
+create_fedora()
+{
+	@bindir@/lxcu-start.sh -n $name
+	std_cmd_err_handler $?
+
+	# Set dnf to keep download only packagfes in the cache.
+	echo "keepcache=True" | \
+		sudo tee -a $contlocation/$name/rootfs/etc/dnf/dnf.conf
+	std_cmd_err_handler $?
+
+	# Set locale.
+	systemd-run --quiet --user --scope -p "Delegate=yes" lxc-attach \
+		-n $name sudo dnf -- -y update --refresh
+	std_cmd_err_handler $?
+	systemd-run --quiet --user --scope -p "Delegate=yes" lxc-attach \
+		-n $name sudo localectl set-locale LANG=en_GB.UTF-8
+	std_cmd_err_handler $?
+	systemd-run --quiet --user --scope -p "Delegate=yes" lxc-attach \
+		-n $name sudo localectl set-keymap gb
+	std_cmd_err_handler $?
+	systemd-run --quiet --user --scope -p "Delegate=yes" lxc-attach \
+		-n $name sudo localectl set-x11-keymap gb
+	std_cmd_err_handler $?
+
+	# Initial installs.
+	systemd-run --quiet --user --scope -p "Delegate=yes" lxc-attach \
+		-n $name sudo dnf -- -y install 'dnf-command(config-manager)'
+	std_cmd_err_handler $?
+
+	# Add the opeSUSE Build Service repository.
+	systemd-run --quiet --user --scope -p "Delegate=yes" lxc-attach \
+		-n $name sudo dnf config-manager -- --add-repo \
+		https://download.opensuse.org/repositories/home:m-grant-prg/Fedora_$rel/home:m-grant-prg.repo
+	std_cmd_err_handler $?
+
+	# Set up the dosab files.
+	systemd-run --quiet --user --scope -p "Delegate=yes" lxc-attach \
+		-n $name sudo dnf -- -y update --refresh
+	std_cmd_err_handler $?
+	systemd-run --quiet --user --scope -p "Delegate=yes" lxc-attach \
+		-n $name sudo dnf -- -y install server-dependency
+	std_cmd_err_handler $?
+	sudo cp -v $etclocation/$dist/$rel/dosab/* \
+		$contlocation/$name/rootfs/etc/dosab
+	std_cmd_err_handler $?
+	sudo chown -Rv 100000:100000  $contlocation/$name/rootfs/etc/dosab
+	std_cmd_err_handler $?
+	systemd-run --quiet --user --scope -p "Delegate=yes" lxc-attach \
+		-n $name sudo dosab.sh
+	std_cmd_err_handler $?
+
+	# Final tidy.
+	systemd-run --quiet --user --scope -p "Delegate=yes" lxc-attach \
+		-n $name sudo dnf -- -y update --refresh
+	std_cmd_err_handler $?
+	systemd-run --quiet --user --scope -p "Delegate=yes" lxc-attach \
+		-n $name sudo dnf -- -y list --autoremove
+	std_cmd_err_handler $?
+
+	create_fedora_type basic
+	if [[ $type != "basic" ]]; then
+		create_fedora_type $type
+	fi
+
+	lxc-stop -n $name
+	std_cmd_err_handler $?
+}
+
 
 ########
 # Main #
@@ -515,6 +616,9 @@ network_config
 case $dist in
 debian)
 	create_deb
+	;;
+fedora)
+	create_fedora
 	;;
 ubuntu)
 	create_deb
diff --git a/src/prg/bash/lxcu/lxcu-project-tmp.sh.in b/src/prg/bash/lxcu/lxcu-project-tmp.sh.in
--- a/src/prg/bash/lxcu/lxcu-project-tmp.sh.in
+++ b/src/prg/bash/lxcu/lxcu-project-tmp.sh.in
@@ -68,6 +68,7 @@
 # 03/09/2021	MG	1.0.5	With lxc v4 lxc start and attach need	#
 #				slightly different privileges. The	#
 #				altered commands also work pre-v4.	#
+# 18/09/2021	MG	1.0.6	Add Fedora support.			#
 #									#
 #########################################################################
 
@@ -80,7 +81,7 @@ set -o pipefail
 ##################
 readonly outputprefix="$(basename $0):"
 
-readonly version=1.0.5				# Script version
+readonly version=1.0.6				# Script version
 readonly packageversion=@pkgversion@		# Package version
 
 readonly etclocation=@sysconfdir@/lxcu		# Path to config directory
@@ -256,6 +257,44 @@ proc_CL()
 	fi
 }
 
+# Perform an APT install
+# No parameters.
+# No return value.
+apt_install()
+{
+	if [[ -e $projectroot/lxcu/$dist/install.list ]]; then
+		cat $projectroot/lxcu/$dist/install.list | xargs \
+			systemd-run --quiet --user --scope -p "Delegate=yes" \
+			lxc-attach -n $project sudo apt-get -- -y install
+		std_cmd_err_handler $?
+	fi
+	if [[ -e $projectroot/lxcu/$dist/$rel/install.list ]]; then
+		cat $projectroot/lxcu/$dist/$rel/install.list | xargs \
+			systemd-run --quiet --user --scope -p "Delegate=yes" \
+			lxc-attach -n $project sudo apt-get -- -y install
+		std_cmd_err_handler $?
+	fi
+}
+
+# Perform a dnf install
+# No parameters.
+# No return value.
+dnf_install()
+{
+	if [[ -e $projectroot/lxcu/$dist/install.list ]]; then
+		cat $projectroot/lxcu/$dist/install.list | xargs \
+			systemd-run --quiet --user --scope -p "Delegate=yes" \
+			lxc-attach -n $project sudo dnf -- -y install
+		std_cmd_err_handler $?
+	fi
+	if [[ -e $projectroot/lxcu/$dist/$rel/install.list ]]; then
+		cat $projectroot/lxcu/$dist/$rel/install.list | xargs \
+			systemd-run --quiet --user --scope -p "Delegate=yes" \
+			lxc-attach -n $project sudo dnf -- -y install
+		std_cmd_err_handler $?
+	fi
+}
+
 
 ########
 # Main #
@@ -280,18 +319,21 @@ std_cmd_err_handler $?
 @bindir@/lxcu-start.sh -n $project
 std_cmd_err_handler $?
 
-if [[ -e $projectroot/lxcu/$dist/install.list ]]; then
-	cat $projectroot/lxcu/$dist/install.list \
-		| xargs systemd-run --quiet --user --scope -p "Delegate=yes" \
-		lxc-attach -n $project sudo apt-get -- -y install
-	std_cmd_err_handler $?
-fi
-if [[ -e $projectroot/lxcu/$dist/$rel/install.list ]]; then
-	cat $projectroot/lxcu/$dist/$rel/install.list \
-		| xargs systemd-run --quiet --user --scope -p "Delegate=yes" \
-		lxc-attach -n $project sudo apt-get -- -y install
-	std_cmd_err_handler $?
-fi
+case $dist in
+debian)
+	apt_install
+	;;
+fedora)
+	dnf_install
+	;;
+ubuntu)
+	apt_install
+	;;
+*)
+	output "Invalid distribution" 1
+	script_exit 64
+	;;
+esac
 
 systemd-run --quiet --user --scope -p "Delegate=yes" lxc-attach -n $project \
 	cp -- -vr $project build
diff --git a/src/prg/bash/lxcu/lxcu-upgrade.sh.in b/src/prg/bash/lxcu/lxcu-upgrade.sh.in
--- a/src/prg/bash/lxcu/lxcu-upgrade.sh.in
+++ b/src/prg/bash/lxcu/lxcu-upgrade.sh.in
@@ -73,6 +73,7 @@
 # 22/08/2021	MG	1.0.7	All config files are now under dist/rel	#
 #				AOT just dist.				#
 # 03/09/2021	MG	1.0.8	With lxc v4 lxc start and attach need	#
+# 18/09/2021	MG	1.0.9	Add Fedora support.			#
 #									#
 #########################################################################
 
@@ -85,7 +86,7 @@ set -o pipefail
 ##################
 readonly outputprefix="$(basename $0):"
 
-readonly version=1.0.8				# Script version
+readonly version=1.0.9				# Script version
 readonly packageversion=@pkgversion@		# Package version
 
 readonly etclocation=@sysconfdir@/lxcu		# Path to config directory
@@ -300,6 +301,51 @@ upgrade_deb()
 	std_cmd_err_handler $?
 }
 
+# Upgrade the specified type of Fedora container.
+# Parameters - $1 is the type to upgrade.
+# No return value.
+upgrade_fedora_type()
+{
+	if [[ -e $etclocation/$dist/$rel/$1/install.list ]]; then
+		cat $etclocation/$dist/$rel/$1/install.list \
+			| xargs systemd-run --quiet --user --scope \
+			-p "Delegate=yes" lxc-attach -n $name \
+			sudo dnf -- -y install
+		std_cmd_err_handler $?
+	fi
+	if [[ -e $etclocation/$dist/$rel/$1/cache.list ]]; then
+		cat $etclocation/$dist/$rel/$1/cache.list \
+			| xargs systemd-run --quiet --user --scope \
+			-p "Delegate=yes" lxc-attach -n $name \
+			sudo dnf -- -y install --downloadonly
+		std_cmd_err_handler $?
+	fi
+}
+
+# Upgrade a Fedora container.
+# No parameters.
+# No return value.
+upgrade_fedora()
+{
+	@bindir@/lxcu-start.sh -n $name
+	std_cmd_err_handler $?
+
+	systemd-run --quiet --user --scope -p "Delegate=yes" lxc-attach \
+		-n $name sudo dnf -- -y update --refresh
+	std_cmd_err_handler $?
+	systemd-run --quiet --user --scope -p "Delegate=yes" lxc-attach \
+		-n $name sudo dnf -- -y list --autoremove
+	std_cmd_err_handler $?
+
+	upgrade_fedora_type basic
+	if [[ $type != "basic" ]]; then
+		upgrade_fedora_type $type
+	fi
+
+	lxc-stop -n $name
+	std_cmd_err_handler $?
+}
+
 
 ########
 # Main #
@@ -312,6 +358,9 @@ proc_CL "$@"
 case $dist in
 debian)
 	upgrade_deb
+	;;
+fedora)
+	upgrade_fedora
 	;;
 ubuntu)
 	upgrade_deb
